services:
    fhm_mail:
        class: Fhm\MailBundle\Services\Mailer
        arguments: ["@fhm_tools", "@fhm.object.manager"]

    listener.mail.user.mail:
        class: Fhm\MailBundle\Listener\MailListener
        arguments: ["@fhm_mail"]
        tags:
          - { name: kernel.event_subscriber, event: fhm.fhm.mail, method: onMail }