<?php
namespace Fhm\PageBundle\Repository;

use Fhm\FhmBundle\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends FhmRepository
{
    /**
     * Constructor
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }

    /**
     * @return \Doctrine\MongoDB\Query\Builder
     */
    public function getMasters()
    {
        return $this->createQueryBuilder()
            ->field('parent')->in(array('0', null))
            ->sort('name');
    }

    /**
     * @param $idp
     *
     * @return mixed
     */
    public function getSons($idp)
    {
        return $this->createQueryBuilder()
            ->field('parent')->equals($idp)
            ->sort('order')
            ->sort('name')
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param $idp
     *
     * @return mixed
     */
    public function getChilds($idp)
    {
        return $this->createQueryBuilder()
            ->field('parent')->equals($idp)
            ->sort('order')
            ->sort('name')
            ->getQuery()
            ->execute()
            ->toArray();
    }
}