<?php
namespace Fhm\CardBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fhm\FhmBundle\Entity\Repository\FhmRepository;

/**
 * CardIngredientRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardIngredientRepository extends FhmRepository
{
    /**
     * CardIngredientRepository constructor.
     * @param EntityManager $dm
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }

    /**
     * @return mixed
     */
    public function getDefault()
    {
        return $this->createQueryBuilder()->field('default')->equals(true)->field('active')->equals(true)->field(
            'delete'
        )->equals(false)->getQuery()->execute()->toArray();
    }

    /**
     * @param        $card
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getByCard(\Fhm\CardBundle\Entity\Card $card)
    {
        $builder = $this->createQueryBuilder();
        // Parent
        if ($this->parent) {
            $builder->field('parent')->in(array('0', null));
        }
        // Card
        if ($card->getIngredients()->count() > 0) {
            $ids = array();
            foreach ($card->getIngredients() as $ingredient) {
                $ids[] = $ingredient->getId();
            }
            $builder->field('id')->in($ids);
        } else {
            return array();
        }
        // Common
        $builder->field('card.id')->equals($card->getId());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder->getQuery()->execute()->toArray();
    }

    /**
     * @param        $card
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getByCardAll(\Fhm\CardBundle\Entity\Card $card)
    {
        $builder = $this->createQueryBuilder();
        // Parent
        if ($this->parent) {
            $builder->field('parent')->in(array('0', null));
        }
        // Card
        if ($card->getIngredients()->count() > 0) {
            $ids = array();
            foreach ($card->getIngredients() as $ingredient) {
                $ids[] = $ingredient->getId();
            }
            $builder->field('id')->in($ids);
        } else {
            return array();
        }
        // Common
        $builder->field('card.id')->equals($card->getId());
        $this->builderSort($builder);

        return $builder->getQuery()->execute()->toArray();
    }

    /**
     * @param \Fhm\CardBundle\Entity\Card $card
     * @param \Fhm\CardBundle\Entity\CardProduct $product
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getByProduct(
        \Fhm\CardBundle\Entity\Card $card,
        \Fhm\CardBundle\Entity\CardProduct $product
    ) {
        $builder = $this->createQueryBuilder();
        // Parent
        if ($this->parent) {
            $builder->field('parent')->in(array('0', null));
        }
        // Ingredients
        if ($product->getIngredients()->count() > 0) {
            $ids = array();
            foreach ($product->getIngredients() as $ingredient) {
                $ids[] = $ingredient->getId();
            }
            $builder->field('id')->in($ids);
        } else {
            return array();
        }
        // Common
        $builder->field('card.id')->equals($card->getId());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder->getQuery()->execute()->toArray();
    }

    /**
     * @param \Fhm\CardBundle\Entity\Card $card
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getFormCard(\Fhm\CardBundle\Entity\Card $card)
    {
        $builder = $this->createQueryBuilder();
        // Parent
        if ($this->parent) {
            $builder->field('parent')->in(array('0', null));
        }
        // Common
        $builder->field('card.id')->equals($card->getId());
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder;
    }
}