services:
    fhm_card:
        class: Fhm\CardBundle\Services\Card
        arguments: ["@fhm_tools"]

    fhm.twig.card_extension:
        class: Fhm\CardBundle\Twig\CardExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    fhm_card_controller_admin:
        class: Fhm\CardBundle\Controller\AdminController
        arguments: ["@fhm_tools"]

    fhm_card_controller_front:
        class: Fhm\CardBundle\Controller\FrontController
        arguments: ["@fhm_tools"]

    fhm_card_controller_api:
        class: Fhm\CardBundle\Controller\ApiController
        arguments: ["@fhm_tools"]

    fhm_card_controller_category_admin:
        class: Fhm\CardBundle\Controller\Category\AdminController
        arguments: ["@fhm_tools"]

    fhm_card_controller_category_api:
        class: Fhm\CardBundle\Controller\Category\ApiController
        arguments: ["@fhm_tools"]

    fhm_card_controller_category_front:
        class: Fhm\CardBundle\Controller\Category\FrontController
        arguments: ["@fhm_tools"]

    fhm_card_controller_product_admin:
        class: Fhm\CardBundle\Controller\Product\AdminController
        arguments: ["@fhm_tools"]

    fhm_card_controller_product_api:
        class: Fhm\CardBundle\Controller\Product\ApiController
        arguments: ["@fhm_tools"]

    fhm_card_controller_product_front:
        class: Fhm\CardBundle\Controller\Product\FrontController
        arguments: ["@fhm_tools"]

    fhm_card_controller_ingredient_admin:
        class: Fhm\CardBundle\Controller\Ingredient\AdminController
        arguments: ["@fhm_tools"]

    fhm_card_controller_ingredient_api:
        class: Fhm\CardBundle\Controller\Ingredient\ApiController
        arguments: ["@fhm_tools"]

    fhm_card_controller_ingredient_front:
        class: Fhm\CardBundle\Controller\Ingredient\FrontController
        arguments: ["@fhm_tools"]