services:
    fhm_card:
        class: Fhm\CardBundle\Services\Card
        arguments: ["@fhm_tools"]

    fhm.twig.card_extension:
        class: Fhm\CardBundle\Twig\CardExtension
        tags:
            - { name: twig.extension }