<?php
namespace Fhm\NewsBundle\Document\Repository;

use Fhm\FhmBundle\Document\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Fhm\NewsBundle\Document\News;

/**
 * NewsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsGroupRepository extends FhmRepository
{
    /**
     * NewsGroupRepository constructor.
     * @param DocumentManager $dm
     * @param UnitOfWork $uow
     * @param ClassMetadata $class
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }


    /**
     * @return array
     */
    public function getListByNews($news)
    {
        $ret = [];
        if ($news instanceof News) {
            $builder = $this->createQueryBuilder()
                ->field('news')->includesReferenceTo($news)
                ->field('active')->equals(true)
                ->field('delete')->equals(false);
            $ret = $builder->getQuery()->execute();
        }

        return $ret;
    }
}