#Common fonfiguration for all environements
imports:
    - { resource: '../parameters.yml' }
    - { resource: '../service/services.yml' }

sensio_framework_extra:
     request:
         converters: true
         auto_convert: false

parameters:
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl
    app.notifications.email_sender: anonymous@example.com

# Basic configuration for the Symfony framework features
framework:
    ide: sublime
    esi:             { enabled: true }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: "FhmFhm/Template/hinclude.html.twig"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    serializer:
        enabled: true

# Twig Configuration (used for rendering application templates)
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false
    globals:
        project: "%project%"
        mailer: "%fhm_mailer%"
        oauth_facebook_id: "%oauth.facebook.id%"
        switch_roles:
            ROLE_USER: 'ROLE_USER'
            ROLE_MEMBER: 'ROLE_MEMBER'
            ROLE_MODERATOR: 'ROLE_MODERATOR'
            ROLE_ADMIN: 'ROLE_ADMIN'

        instance: "@fhm.instance.data"
    form_themes:
        - 'FhmFhmBundle:Form:fields.html.twig'
        - 'FhmMediaBundle:Form:fields.html.twig'
#        - 'FhmMenuBundle:Form:fields.html.twig'

# Doctrine Configuration (used to access databases and manipulate their information)
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Swiftmailer Configuration (used to send emails)
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# Oauth
hwi_oauth:
    firewall_names:        [main]
    resource_owners:
        facebook:
            type:          facebook
            client_id:     "%oauth.facebook.id%"
            client_secret: "%oauth.facebook.secret%"
            scope:         "public_profile,email"
            infos_url: "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            options:
                display:   popup
            paths:
                email:          email
                profilepicture: picture.data.url
        twitter:
            type:          twitter
            client_id:     "%oauth.twitter.id%"
            client_secret: "%oauth.twitter.secret%"
            scope:         ""
        google:
            type:          google
            client_id:     "%oauth.google.id%"
            client_secret: "%oauth.google.secret%"
            scope:         "email profile"
    http_client:
        verify_peer:       false

# Google Map
ivory_google_map:
    geocoder:
        format: json
        client: httplug.client.default
        message_factory: httplug.message_factory.default
    map:
        api_key: AIzaSyAF_6nXrBELMKyL9jFeElmg7DT6plv9afQ
        language: "%locale%"

# EWZ Recaptcha
ewz_recaptcha:
    public_key:  "%recaptcha_public_key%"
    private_key: "%recaptcha_private_key%"
    locale_key:  "%locale%"
    enabled:     true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:foundation_v5_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template