services:
    fhm.historic.service:
        class: Fhm\HistoricBundle\EventListener\HistoricService
        arguments: ["@serializer", "@request_stack"]
        tags:
             - { name: doctrine_mongodb.odm.event_subscriber, event: postUpdate , connection: default}
             - { name: doctrine_mongodb.odm.event_subscriber, event: postPersist, connection: default}
             - { name: doctrine_mongodb.odm.event_subscriber, event: postFlush, connection: default}

