services:
    fhm.historic.service:
        class: Fhm\HistoricBundle\EventListener\HistoricService
        arguments: ["@request_stack"]
        tags:
             - { name: doctrine_mongodb.odm.event_subscriber, event: postUpdate , connection: default}
             - { name: doctrine_mongodb.odm.event_subscriber, event: postPersist, connection: default}
             - { name: doctrine_mongodb.odm.event_subscriber, event: postFlush, connection: default}

    fhm.historic.manager:
        class: Fhm\HistoricBundle\Service\HistoricManager
        arguments: ["@fhm_database_manager", "@fhm.hydrator"]

    fhm.hydrator:
        class: Fhm\HistoricBundle\Hydrator\Hydrator