services:

    fhm_tools:
        class: Fhm\FhmBundle\Services\Tools
        arguments: ["@service_container"]

    fhm_schedules:
        class: Fhm\FhmBundle\Services\Schedules
        arguments: ["@translator.default", "@templating"]

    fhm.twig.fhm_extension:
        class: Fhm\FhmBundle\Twig\FhmExtension
        arguments: ["@session", "@translator.default"]
        tags:
            - { name: twig.extension }

    fhm.event.listener:
        class: Fhm\FhmBundle\EventListener\FhmEventListener
        arguments: ["@templating", "@security.token_storage", "@security.authorization_checker", "%project%"]
        tags:
            - { name: kernel.event_subscriber, event: kernel.request, method: onKernelRequest }

    fhm.instance.data:
        class: Fhm\FhmBundle\EventListener\FhmInstance
        tags:
            - { name: kernel.event_subscriber, event: kernel.controller, method: onKernelController }

    fhm.form.type.autocomplete:
        class: Fhm\FhmBundle\Form\Type\AutocompleteType
        arguments: ["@router"]
        tags:
            - { name: form.type, alias: autocomplete }

    fhm.form.type.schedules:
        class: Fhm\FhmBundle\Form\Type\SchedulesType
        arguments: ["@translator.default", "@templating"]
        tags:
            - { name: form.type, alias: schedules }

    fhm.entity.manager:
        class: Fhm\Manager\FhmEntityManager
        arguments: ["@fhm_database_manager"]

    fhm.document.manager:
        class: Fhm\Manager\FhmDocumentManager
        arguments: ["@fhm_database_manager"]
