services:

    fhm_tools:
        class: Fhm\FhmBundle\Services\Tools
        arguments: ["@service_container"]

    fhm_schedules:
        class: Fhm\FhmBundle\Services\Schedules
        arguments: ["@service_container"]

    fhm.twig.fhm_extension:
        class: Fhm\FhmBundle\Twig\FhmExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    fhm.event.listener:
        class: Fhm\FhmBundle\EventListener\FhmEventListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_subscriber, event: kernel.request, method: onKernelRequest }

    fhm.instance.data:
        class: Fhm\FhmBundle\EventListener\FhmInstance
        tags:
            - { name: kernel.event_subscriber, event: kernel.controller, method: onKernelController }

    fhm.form.type.autocomplete:
        class: Fhm\FhmBundle\Form\Type\AutocompleteType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: autocomplete }

    fhm.form.type.schedules:
        class: Fhm\FhmBundle\Form\Type\SchedulesType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: schedules }

    fhm_historic:
            class: Fhm\FhmBundle\Services\HistoricService
            arguments: ["@service_container"]