services:

    fhm_tools:
        class: Fhm\FhmBundle\Services\Tools
        arguments: ["@service_container"]

    fhm_schedules:
        class: Fhm\FhmBundle\Services\Schedules
        arguments: ["@service_container"]

    fhm.twig.fhm_extension:
        class: Fhm\FhmBundle\Twig\FhmExtension
        arguments: ["@fhm_schedules","@session", "@translator.default"]
        tags:
            - { name: twig.extension }

    fhm.event.listener:
        class: Fhm\FhmBundle\EventListener\FhmEventListener
        arguments: ["@templating", "@security.token_storage", "@security.authorization_checker", "@project_twig_global","%project%"]
        tags:
            - { name: kernel.event_subscriber, event: kernel.request, method: onKernelRequest }

    fhm.instance.data:
        class: Fhm\FhmBundle\EventListener\FhmInstance
        tags:
            - { name: kernel.event_subscriber, event: kernel.controller, method: onKernelController }

    fhm.form.type.autocomplete:
        class: Fhm\FhmBundle\Form\Type\AutocompleteType
        arguments: ["@router"]
        tags:
            - { name: form.type, alias: autocomplete }

    fhm.form.type.schedules:
        class: Fhm\FhmBundle\Form\Type\SchedulesType
        arguments: ["@fhm_schedules"]
        tags:
            - { name: form.type, alias: schedules }

    fhm.object.manager:
        class: Fhm\FhmBundle\Manager\FhmObjectManager
        arguments: ["@fhm.database.manager", "%database_manager%"]
