services:
    fhm_grouping:
        class: Fhm\FhmBundle\Services\Grouping
        arguments: ['@service_container']

    fhm_schedules:
        class: Fhm\FhmBundle\Services\Schedules
        arguments: ['@service_container']

    fhm.twig.fhm_extension:
        class: Fhm\FhmBundle\Twig\FhmExtension
        arguments: ['@service_container', '@markdown', '%app_locales%']
        tags:
            - { name: twig.extension }

    fhm.event.listener:
        class: Fhm\FhmBundle\EventListener\FhmEventListener
#        calls:
#            - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    fhm.form.type.autocomplete:
        class: Fhm\FhmBundle\Form\Type\AutocompleteType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: autocomplete }

    fhm.form.type.schedules:
        class: Fhm\FhmBundle\Form\Type\SchedulesType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: schedules }