services:
    mappicker.nomap:
        class: Fhm\MapPickerBundle\Services\MapNoMap
        arguments: ["@templating", "%fhm_mappicker%"]

    mappicker.france_domtom:
        class: Fhm\MapPickerBundle\Services\MapFranceDomtom
        arguments: ["@templating", "%fhm_mappicker%"]

    mappicker.france_region:
        class: Fhm\MapPickerBundle\Services\MapFranceRegion
        arguments: ["@templating", "%fhm_mappicker%"]
