imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.mongo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false
    globals:
        project: %project%
        mailer: %fhm_mailer%
    form:
        resources:
            - 'FhmFhmBundle:Form:fields.html.twig'
            - 'FhmMediaBundle:Form:fields.html.twig'
            - 'FhmMenuBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Fhm\UserBundle\Document\User
    from_email:
        address:     %fhm_mailer.noreply%
        sender_name: noreply
    service:
        mailer: fhm_user.mailer.twig_swift
    profile:
        form:
            type: FhmUpdate
    change_password:
        form:
            type: FhmPassword
    resetting:
        form:
            type: FhmResetting
    registration:
        form:
            type: FhmCreate
        confirmation:
            enabled: true

# Oauth
hwi_oauth:
    firewall_name:         main
    resource_owners:
        facebook:
            type:          facebook
            client_id:     %oauth.facebook.id%
            client_secret: %oauth.facebook.secret%
            scope:         email
            options:
                display:   popup
        twitter:
            type:          twitter
            client_id:     %oauth.twitter.id%
            client_secret: %oauth.twitter.secret%
            scope:         ""
        google:
            type:          google
            client_id:     %oauth.google.id%
            client_secret: %oauth.google.secret%
            scope:         "email profile"
    http_client:
        verify_peer:       false

# MongoDB
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
                username: %mongodb_username%
                password: %mongodb_password%
                replicaSet: %mongodb_replicaSet%
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true

# Google Map
ivory_google_map:
    map:
        width:     "100%"
        height:    "100%"
        language:  %locale%
        auto_zoom: false
        zoom:      3
    pan_control:
        control_position: left_bottom
    geocoder:
        provider:
            locale: %locale%

# EWZ Recaptcha
ewz_recaptcha:
    public_key:  %recaptcha_public_key%
    private_key: %recaptcha_private_key%
    locale_key:  %locale%
    enabled:     true