routing_fhm:
    resource: "routing_fhm.yml"

routing_shop:
    resource: "routing_shop.yml"

routing_other:
    resource: "routing_other.yml"

routing_project:
    resource: "routing_project.yml"

# Toujours laisser ce bundle à la fin.
fhm_error:
    resource: "@FhmErrorBundle/Controller/"
    type:     annotation
    prefix:   /