security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MODERATOR:                     ROLE_USER
        ROLE_ADMIN:                         ROLE_MODERATOR
        ROLE_SUPER_ADMIN:                   ROLE_ADMIN

    providers:
        fos_userbundle:
            id:                             fos_user.user_provider.username
        fhm_userbundle:
            id:                             fhm_user.security.user_provider

    firewalls:
        main:
            pattern:                        ^/
            form_login:
                provider:                   fhm_userbundle
                csrf_provider:              form.csrf_provider
            oauth:
                resource_owners:
                    facebook:               fhm_user_check_facebook
                    twitter:                fhm_user_check_twitter
                    google:                 fhm_user_check_google
                login_path:                 fos_user_security_login
                failure_path:               fos_user_security_login
                check_path:                 fos_user_security_check
                oauth_user_provider:
                    service:                fhm_user.oauth.user_provider
            logout:                         true
            anonymous:                      true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_MODERATOR }
        - { path: ^/mail/, role: ROLE_ADMIN }