services:
    app.redirect_to_preferred_locale_listener:
        class: Fhm\FhmBundle\EventListener\RedirectToPreferredLocaleListener
        arguments: ['@router', '%app_locales%', '%locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo', '%mongo.session.options%']

    fos_user.doctrine_registry:
        alias: doctrine

    mongo.connection:
        class: MongoDoctrine\MongoDB\Connection
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getConnection
        calls:
           - [initialize, []]
    mongo:
        class: Mongo
        factory_service: mongo.connection
        factory_method: getMongo

#    fhm_form.menu_type_extension:
#        class: Fhm\MenuBundle\Form\type\Extension\LinkType
#        tags:
#             - { name: link.type, alias: link }
    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: Fhm\FhmBundle\Utils\Slugger

    markdown:
        class: Fhm\FhmBundle\Utils\Markdown


    # These are the Twig extensions that create new filters and functions for
    # using them in the templates

    twig.extension.intl:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

