#services:
#    session.handler.mongo:
#        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
#        arguments: ['@mongo', '%mongo.session.options%']
#
#    # Use doctrine_mongodb to allow doctrine mapping
#    fos_user.doctrine_registry:
#        alias: doctrine_mongodb
#
#    mongo.connection:
#        class: Doctrine\MongoDB\Connection
#        factory: ["@doctrine.odm.mongodb.document_manager", getConnection]
#        calls:
#            - [initialize, []]
#
#    mongo:
#        class: Mongo
#        factory: ["@mongo.connection", getMongo]
#
#    twig.extension.intl:
#        class: Twig_Extensions_Extension_Intl
#        tags:
#            - { name: twig.extension }