services:
#    fhm_article.example:
#        class: Fhm\ArticleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     fhm.article_voter:
            class: Fhm\ArticleBundle\Security\ArticleVoter
            tags:
                - { name: security.voter }
            # small performance boost
            public: false
