services:
#    fhm_article.example:
#        class: Fhm\ArticleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     fhm.article_voter:
            class: Fhm\ArticleBundle\Security\ArticleVoter
            tags:
                - { name: security.voter }
            # small performance boost
            public: false

     fhm_article.converter.doctrine.mongodb:
            class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
            arguments: ['@doctrine_mongodb']
            tags:
                - { name: request.param_converter, priority: -2, converter: doctrine_mongo_db_param_converter}
