services:
    fhm.twig.media_extension:
        class: Fhm\MediaBundle\Twig\MediaExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    fhm.twig.media_tag_extension:
        class: Fhm\MediaBundle\Twig\MediaTagExtension
        arguments: ["@fhm_tools"]
        tags:
            - { name: twig.extension }

    fhm.form.type.media:
        class: Fhm\MediaBundle\Form\Type\MediaType
        tags:
            - { name: form.type, alias: media }

    fhm_form.media_type_extension:
        class: Fhm\MediaBundle\Form\Extension\MediaTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType, alias: file }

    fhm_media_local:
        class: Fhm\MediaBundle\Services\Local
        arguments: ["@fhm_tools", "@kernel"]

    fhm_media_s3:
        class: Fhm\MediaBundle\Services\S3
        arguments: ["@fhm_tools", "@kernel"]