services:
    fhm_mail:
        class: Core\MailBundle\Services\Mailer
        arguments: ["@mailer", "@templating"]
    listener.mail.user.mail:
        class: Core\MailBundle\Listener\MailListener
        arguments: ["@service_container"]
        tags:
          - { name: kernel.event_listener, event: fhm.fhm.mail, method: onMail }