<?php
namespace Fhm\GeolocationBundle\Document\Repository;

use Fhm\FhmBundle\Document\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use MyProject\Proxies\__CG__\stdClass;

/**
 * GeolocationRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeolocationRepository extends FhmRepository
{
    /**
     * GeolocationRepository constructor.
     * @param DocumentManager $dm
     * @param UnitOfWork $uow
     * @param ClassMetadata $class
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }

    /**
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function findUniqueBy($data)
    {
        return $data;
    }
}