<?php
namespace Fhm\PartnerBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fhm\FhmBundle\Entity\Repository\FhmRepository;

/**
 * PartnerRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends FhmRepository
{
    /**
     * PartnerRepository constructor.
     * @param EntityManager $dm
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }

    /**
     * @param string $search
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getFrontIndex($search = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();

        // Dates
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_start')->equals(null))
                ->addOr($builder->expr()->field('date_start')->lt(new \DateTime()))
        );
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_end')->equals(null))
                ->addOr($builder->expr()->field('date_end')->gt(new \DateTime()))
        );
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param string $search
     * @param string $grouping
     *
     * @return int
     * @throws \Doctrine\ORM\ORMException
     */
    public function getFrontCount($search = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();

        // Dates
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_start')->equals(null))
                ->addOr($builder->expr()->field('date_start')->lt(new \DateTime()))
        );
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_end')->equals(null))
                ->addOr($builder->expr()->field('date_end')->gt(new \DateTime()))
        );
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return count($builder
            ->getQuery()
            ->execute()
            ->toArray());
    }

    /**
     * @param \Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup
     * @param string                             $search
     * @param int                                $page
     * @param int                                $count
     *
     * @return mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getPartnerByGroupIndex(\Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup, $search = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Global
        if($partnergroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('partnergroups.id')->equals($partnergroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('partnergroups.id')->equals($partnergroup->getId());
        }
        // Dates
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_start')->equals(null))
                ->addOr($builder->expr()->field('date_start')->lt(new \DateTime()))
        );
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_end')->equals(null))
                ->addOr($builder->expr()->field('date_end')->gt(new \DateTime()))
        );
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param \Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup
     * @param string                             $search
     *
     * @return mixed
     */
    public function getPartnerByGroupCount(\Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup, $search = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Global
        if($partnergroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('partnergroups.id')->equals($partnergroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('partnergroups.id')->equals($partnergroup->getId());
        }
        // Dates
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_start')->equals(null))
                ->addOr($builder->expr()->field('date_start')->lt(new \DateTime()))
        );
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_end')->equals(null))
                ->addOr($builder->expr()->field('date_end')->gt(new \DateTime()))
        );
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }

    /**
     * @param \Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup
     *
     * @return int
     * @throws \Doctrine\ORM\ORMException
     */
    public function getPartnerByGroupAll(\Fhm\PartnerBundle\Entity\PartnerGroup $partnergroup)
    {
        $builder = $this->createQueryBuilder();
        // Global
        if($partnergroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('partnergroups.id')->equals($partnergroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('partnergroups.id')->equals($partnergroup->getId());
        }
        // Dates
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_start')->equals(null))
                ->addOr($builder->expr()->field('date_start')->lt(new \DateTime()))
        );
        $builder->addAnd(
            $builder->expr()
                ->addOr($builder->expr()->field('date_end')->equals(null))
                ->addOr($builder->expr()->field('date_end')->gt(new \DateTime()))
        );
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute();
    }
}