services:
    fhm_map:
        class: Core\GeolocationBundle\Services\Map
        arguments: ["@service_container"]

    fhm_marker:
        class: Core\GeolocationBundle\Services\Marker
        arguments: ["@templating", "@service_container"]

    fhm_geocoder:
        class: Core\GeolocationBundle\Services\Geocoder
        arguments: ["@service_container"]

    fhm.twig.geolocation_extension:
        class: Core\GeolocationBundle\Twig\GeolocationExtension
        tags:
            - { name: twig.extension }