services:
    fhm_gallery_controller_admin:
        class: Fhm\GalleryBundle\Controller\AdminController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_front:
        class: Fhm\GalleryBundle\Controller\FrontController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_api:
        class: Fhm\GalleryBundle\Controller\ApiController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_album_admin:
        class: Fhm\GalleryBundle\Controller\Album\AdminController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_album_front:
        class: Fhm\GalleryBundle\Controller\Album\FrontController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_album_api:
        class: Fhm\GalleryBundle\Controller\Album\ApiController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_item_admin:
        class: Fhm\GalleryBundle\Controller\Item\AdminController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_item_front:
        class: Fhm\GalleryBundle\Controller\Item\FrontController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_item_api:
        class: Fhm\GalleryBundle\Controller\Item\ApiController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_video_admin:
        class: Fhm\GalleryBundle\Controller\Video\AdminController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_video_front:
        class: Fhm\GalleryBundle\Controller\Video\FrontController
        arguments: ["@fhm_tools"]

    fhm_gallery_controller_video_api:
        class: Fhm\GalleryBundle\Controller\Video\ApiController
        arguments: ["@fhm_tools"]