<?php
namespace Fhm\FhmBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * MenuRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends FhmRepository
{
    /**
     * MenuRepository constructor.
     * @param EntityManager $dm
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }

    /**
     * @return \Doctrine\ODM\MongoDB\Query\Builder
     */
    public function getFormEnable()
    {
        $builder = $this->createQueryBuilder();
        // Common
        $builder->field('parent')->in(array('0', null));
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('order');
        $builder->sort('name');

        return $builder;
    }

    /**
     * @param $idp
     *
     * @return mixed
     */
    public function getSons($idp)
    {
        return $this->createQueryBuilder()->field('parent')->equals($idp)->sort('order')->sort('name')->getQuery(
            )->execute()->toArray();
    }

    /**
     * @param $idp
     *
     * @return object
     * @throws \Doctrine\ODM\MongoDB\LockException
     */
    public function getTree($idp)
    {
        $current = $this->find($idp);
        $current->branchs = array();
        $branchs = $current->getChilds();
        foreach ($branchs as $branch) {
            $current->branchs[] = $this->getTree($branch->getId());
        }

        return $current;
    }

    /**
     * @param $idp
     *
     * @return array
     * @throws \Doctrine\ODM\MongoDB\LockException
     */
    public function getTreeMap($idp)
    {
        $current = $this->find($idp);
        $map = array();
        if ($current->getParent() != '0') {
            $map = array_merge($map, $this->getTreeMap($current->getParent()));
        }
        $map[] = $current;

        return $map;
    }
}