<?php
namespace Fhm\FhmBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * SiteRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends FhmRepository
{
    /**
     * SiteRepository constructor.
     * @param EntityManager $dm
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }

    /**
     * @return mixed
     */
    public function getDefault()
    {
        $builder = $this->createQueryBuilder('');
        return $builder
            ->andWhere('default' == true)
            ->getMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * void function
     */
    public function resetDefault()
    {
        $builder = $this->createQueryBuilder();

        $builder
            ->field('default')->equals(true)
            ->field('default')->set(false)
            ->update()
            ->multiple(true)
            ->getQuery()
            ->execute();
    }
}