<?php
namespace Fhm\WorkflowBundle\Repository;

use Fhm\FhmBundle\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * WorkflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowRepository extends FhmRepository
{
    /**
     * WorkflowRepository constructor.
     * @param DocumentManager $dm
     * @param UnitOfWork $uow
     * @param ClassMetadata $class
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }

    /**
     * @param            $status
     * @param bool|false $enable
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getByStatus($status, $enable=false)
    {
        $builder = $this->createQueryBuilder();
        $builder->field('status')->equals($status);
        if($enable)
        {
            $builder->field('active')->equals(true);
            $builder->field('delete')->equals(false);
        }
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param            $step
     * @param bool|false $enable
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getByStep($step, $enable=false)
    {
        $builder = $this->createQueryBuilder();
        $builder->field('step.id')->equals($step);
        if($enable)
        {
            $builder->field('active')->equals(true);
            $builder->field('delete')->equals(false);
        }
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }
}