<?php
namespace Fhm\NotificationBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fhm\FhmBundle\Entity\Repository\FhmRepository;

/**
 * NotificationRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends FhmRepository
{
    /**
     * NotificationRepository constructor.
     * @param EntityManager $dm
     * @param ClassMetadata $class
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }

    /**
     * @param $user
     *
     * @return int|mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getIndexNew($user)
    {
        if (!$user) {
            return 0;
        }
        $builder = $this->createQueryBuilder();
        $builder->field('user.id')->equals($user->getId());
        $builder->field('new')->equals(true);
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_create', 'desc');

        return $builder->getQuery()->execute()->toArray();
    }

    /**
     * @param $user
     *
     * @return int|mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getIndexAll($user)
    {
        if (!$user) {
            return 0;
        }
        $builder = $this->createQueryBuilder();
        $builder->field('user.id')->equals($user->getId());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_create', 'desc');

        return $builder->getQuery()->execute()->toArray();
    }

    /**
     * @param $user
     *
     * @return int|mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getCountNew($user)
    {
        if (!$user) {
            return 0;
        }
        $builder = $this->createQueryBuilder();
        $builder->field('user.id')->equals($user->getId());
        $builder->field('new')->equals(true);
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder->count()->getQuery()->execute();
    }

    /**
     * @param $user
     *
     * @return int|mixed
     * @throws \Doctrine\ORM\ORMException
     */
    public function getCountAll($user)
    {
        if (!$user) {
            return 0;
        }
        $builder = $this->createQueryBuilder();
        $builder->field('user.id')->equals($user->getId());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder->count()->getQuery()->execute();
    }
}