<?php
namespace Fhm\FhmBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * SiteRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends FhmRepository
{
    /**
     * SiteRepository constructor.
     * @param DocumentManager $dm
     * @param UnitOfWork $uow
     * @param ClassMetadata $class
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }

    /**
     * @return mixed
     */
    public function getDefault()
    {
        $builder = $this->createQueryBuilder();

        return $builder
            ->field('default')->equals(true)
            ->limit(1)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * void function
     */
    public function resetDefault()
    {
        $builder = $this->createQueryBuilder();

        $builder
            ->field('default')->equals(true)
            ->field('default')->set(false)
            ->update()
            ->multiple(true)
            ->getQuery()
            ->execute();
    }
}