services:
    fhm_user.profile.form.type:
        class: Fhm\UserBundle\Form\Type\Front\UpdateType
        arguments: ["@security.token_storage", "%fos_user.model.user.class%"]
        tags:
          - { name: form.type, alias: FhmUpdate }

    fhm_user.registration.form.type:
        class: Fhm\UserBundle\Form\Type\Front\CreateType
        arguments: ["%fos_user.model.user.class%"]
        tags:
          - { name: form.type, alias: FhmCreate }

    fhm_user.change_password.form.type:
        class: Fhm\UserBundle\Form\Type\Front\PasswordType
        arguments: ["%fos_user.model.user.class%"]
        tags:
          - { name: form.type, alias: FhmPassword }

    fhm_user.resetting.form.type:
        class: Fhm\UserBundle\Form\Type\Front\ResettingType
        arguments: ["%fos_user.model.user.class%"]
        tags:
          - { name: form.type, alias: FhmResetting }

    fhm_user_activity_listener:
        class: Fhm\UserBundle\EventListener\ActivityListener
        arguments: ["@security.token_storage", "@doctrine_mongodb.odm.default_document_manager"]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    fhm_user.mailer.twig_swift:
        class: Fhm\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            - "@fhm_mail"
            - {template: { confirmation: "%fos_user.registration.confirmation.template%",   resetting: "%fos_user.resetting.email.template%" }, from_email: { confirmation: "%fos_user.registration.confirmation.from_email%", resetting: "%fos_user.resetting.email.from_email%" }}

    fhm_user.security.user_provider:
        class: Fhm\UserBundle\Security\UserProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    fhm_user.oauth.user_provider:
        class: Fhm\UserBundle\OAuth\UserProvider
        arguments: ["@fos_user.user_manager", {facebook: id_facebook, google: id_gplus, twitter: id_twitter}]
