<?php
namespace Fhm\EventBundle\Repository;

use Fhm\FhmBundle\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * EventRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends FhmRepository
{
    /**
     * Constructor
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
    }

    /**
     * @param string $search
     * @param int    $page
     * @param int    $count
     * @param string $grouping
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontIndex($search = "", $page = 1, $count = 5, $grouping = "")
    {
        $builder = $search ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Pagination
        if($page > 0 && $count > 0)
        {
            $builder->limit($count);
            $builder->skip(($page - 1) * $count);
        }
        // Common
        $builder->field('date_end')->gt(new \DateTime());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_start');
        $builder->sort('order');
        $builder->sort('name');

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param string $search
     * @param string $grouping
     *
     * @return int
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontCount($search = "", $grouping = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Common
        $builder->field('date_end')->gt(new \DateTime());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }

    /**
     * @param \Fhm\EventBundle\Document\EventGroup $eventgroup
     * @param string                               $search
     * @param int                                  $page
     * @param int                                  $count
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getEventByGroupIndex(\Fhm\EventBundle\Document\EventGroup $eventgroup, $search = "", $page = 1, $count = 5)
    {
        $builder = (($page > 0 && $count > 0) && $search) ? $this->search($search) : $this->createQueryBuilder();
        // Global
        if($eventgroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('eventgroups.id')->equals($eventgroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('eventgroups.id')->equals($eventgroup->getId());
        }
        // Pagination
        if($page > 0 && $count > 0)
        {
            $builder->limit($count);
            $builder->skip(($page - 1) * $count);
        }
        // Common
        $builder->field('date_end')->gt(new \DateTime());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_start');
        $builder->sort('order');
        $builder->sort('name');

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param \Fhm\EventBundle\Document\EventGroup $eventgroup
     * @param string                               $search
     *
     * @return mixed
     */
    public function getEventByGroupCount(\Fhm\EventBundle\Document\EventGroup $eventgroup, $search = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Global
        if($eventgroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('eventgroups.id')->equals($eventgroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('eventgroups.id')->equals($eventgroup->getId());
        }
        // Common
        $builder->field('date_end')->gt(new \DateTime());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }

    /**
     * @param \Fhm\EventBundle\Document\EventGroup $eventgroup
     *
     * @return int
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getEventByGroupAll(\Fhm\EventBundle\Document\EventGroup $eventgroup)
    {
        $builder = $this->createQueryBuilder();
        // Global
        if($eventgroup->getAddGlobal())
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('eventgroups.id')->equals($eventgroup->getId()))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        else
        {
            $builder->field('eventgroups.id')->equals($eventgroup->getId());
        }
        // Common
        $builder->field('date_end')->gt(new \DateTime());
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_start');
        $builder->sort('order');
        $builder->sort('name');

        return $builder
            ->getQuery()
            ->execute();
    }

    /**
     * @param string $grouping
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getEventEnable($grouping = "")
    {
        $builder = $this->createQueryBuilder();
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_start');
        $builder->sort('order');
        $builder->sort('name');

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param        $date
     * @param string $search
     * @param int    $page
     * @param int    $count
     * @param string $grouping
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontDateIndex($date, $search = "", $page = 1, $count = 5, $grouping = "")
    {
        $builder = $search ? $this->search($search) : $this->createQueryBuilder();
        $dateMin = new \DateTime($date);
        $dateMin->setTime(0, 0, 0);
        $dateMax = new \DateTime($date);
        $dateMax->setTime(23, 59, 59);
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Pagination
        if($page > 0 && $count > 0)
        {
            $builder->limit($count);
            $builder->skip(($page - 1) * $count);
        }
        // Dates
        $builder->field('date_start')->lte($dateMax);
        $builder->field('date_end')->gte($dateMin);
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $builder->sort('date_start');
        $builder->sort('order');
        $builder->sort('name');

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param string $search
     * @param string $grouping
     *
     * @return int
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontDateCount($date, $search = "", $grouping = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        $dateMin = new \DateTime($date);
        $dateMin->setTime(0, 0, 0);
        $dateMax = new \DateTime($date);
        $dateMax->setTime(23, 59, 59);
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Dates
        $builder->field('date_start')->lte($dateMax);
        $builder->field('date_end')->gte($dateMin);
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }
}