services:
    fhm_note:
        class: Fhm\NoteBundle\Services\Note
        arguments: ["@fhm_tools"]

    twig.extension.note:
        class: Fhm\NoteBundle\Twig\NoteExtension
        arguments: ["@fhm_note", "%kernel.root_dir%", "%fhm_note%"]
        tags:
            - { name: twig.extension }