services:
    fhm_grouping_site:
        class: Fhm\SiteBundle\Services\Grouping
        arguments: [@fhm_tools, $twig]

    fhm_site_controller_admin:
        class: Fhm\SiteBundle\Controller\AdminController
        arguments: [@fhm_tools]

    fhm_site_controller_front:
        class: Fhm\SiteBundle\Controller\FrontController
        arguments: [@fhm_tools]

    fhm_site_controller_api:
        class: Fhm\SiteBundle\Controller\ApiController
        arguments: [@fhm_tools]