<?php
namespace Fhm\MediaBundle\Repository;

use Fhm\FhmBundle\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * MediaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends FhmRepository
{
    protected $tag;
    protected $filter;
    protected $private;

    /**
     * Constructor
     */
    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        parent::__construct($dm, $uow, $class);
        $this->tag     = "";
        $this->filter  = "";
        $this->private = true;
    }

    /**
     * @param $tag
     *
     * @return $this
     */
    public function setTag($tag)
    {
        $this->tag = $tag;

        return $this;
    }

    /**
     * @param $filter
     *
     * @return $this
     */
    public function setFilter($filter)
    {
        if($filter !== '')
        {
            $filter       = str_replace('/*', '', $filter);
            $filter       = str_replace('.', '', $filter);
            $this->filter = explode(',', $filter);
        }

        return $this;
    }

    /**
     * @param $private
     *
     * @return $this
     */
    public function setPrivate($private)
    {
        $this->private = $private;

        return $this;
    }

    /**
     * @param string $search
     * @param int    $page
     * @param int    $count
     * @param string $grouping
     * @param bool   $roleSuperAdmin
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getAdminIndex($search = "", $page = 1, $count = 5, $grouping = "", $roleSuperAdmin = false)
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Tag
        if($this->tag)
        {
            $builder->field('tags.id')->equals($this->tag);
        }
        // Private
        if(!$this->private)
        {
            $builder->field('private')->equals(false);
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('share')->equals(true))
            );
        }
        // RoleSuperAdmin
        if(!$roleSuperAdmin)
        {
            $builder->field('delete')->equals(false);
        }
        // Pagination
        if($page > 0 && $count > 0)
        {
            $builder->limit($count);
            $builder->skip(($page - 1) * $count);
        }
        // Common
        $this->builderSort($builder);

        return $builder->getQuery()->execute()->toArray();
    }


    /**
     * @param string $search
     * @param string $grouping
     * @param bool   $roleSuperAdmin
     *
     * @return int
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getAdminCount($search = "", $grouping = "", $roleSuperAdmin = false)
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Tag
        if($this->tag)
        {
            $builder->field('tags.id')->equals($this->tag);
        }
        // Private
        if(!$this->private)
        {
            $builder->field('private')->equals(false);
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('share')->equals(true))
            );
        }
        // RoleSuperAdmin
        if(!$roleSuperAdmin)
        {
            $builder->field('delete')->equals(false);
        }

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }

    /**
     * @param string $search
     * @param int    $page
     * @param int    $count
     * @param string $grouping
     *
     * @return mixed
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontIndex($search = "", $page = 1, $count = 5, $grouping = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Tag
        if($this->tag)
        {
            $builder->field('tags.id')->equals($this->tag);
        }
        // Private
        if(!$this->private)
        {
            $builder->field('private')->equals(false);
        }
        // Filter
        if($this->filter)
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('type')->in($this->filter))
                    ->addOr($builder->expr()->field('extension')->in($this->filter))
                    ->addOr($builder->expr()->field('mimeType')->in($this->filter))
            );
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Pagination
        if($page > 0 && $count > 0)
        {
            $builder->limit($count);
            $builder->skip(($page - 1) * $count);
        }
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }

    /**
     * @param string $search
     * @param string $grouping
     *
     * @return int
     * @throws \Doctrine\ODM\MongoDB\MongoDBException
     */
    public function getFrontCount($search = "", $grouping = "")
    {
        $builder = ($search) ? $this->search($search) : $this->createQueryBuilder();
        // Parent
        if($this->parent)
        {
            $builder->field('parent')->in(array('0', null));
        }
        // Tag
        if($this->tag)
        {
            $builder->field('tags.id')->equals($this->tag);
        }
        // Private
        if(!$this->private)
        {
            $builder->field('private')->equals(false);
        }
        // Filter
        if($this->filter)
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('type')->in($this->filter))
                    ->addOr($builder->expr()->field('extension')->in($this->filter))
                    ->addOr($builder->expr()->field('mimeType')->in($this->filter))
            );
        }
        // Grouping
        if($grouping != "")
        {
            $builder->addAnd(
                $builder->expr()
                    ->addOr($builder->expr()->field('grouping')->in((array) $grouping))
                    ->addOr($builder->expr()->field('global')->equals(true))
            );
        }
        // Common
        $builder->field('active')->equals(true);
        $builder->field('delete')->equals(false);

        return $builder
            ->count()
            ->getQuery()
            ->execute();
    }

    /**
     * @param $id
     *
     * @return mixed
     */
    public function getByTag($id)
    {
        $builder = $this->createQueryBuilder();
        // Private
        if(!$this->private)
        {
            $builder->field('private')->equals(false);
        }
        // Common
        $builder->field('tags.id')->equals($id);
        $this->builderSort($builder);

        return $builder
            ->getQuery()
            ->execute()
            ->toArray();
    }
}