services:
    project_twig_global:
        class: Project\DefaultBundle\Services\TwigGlobal
        arguments: ['@service_container']

    fhm_cache:
        class: Project\DefaultBundle\Services\Cache
        arguments: ['@fhm_tools', '@session']

    project_default_controller_front:
        class: Project\DefaultBundle\Controller\FrontController
        arguments: ['@fhm_tools']