services:
    project_twig_global:
        class: Project\DefaultBundle\Services\TwigGlobal
        arguments: ['@fhm_tools', '@session', '@twig']

    project_moderator:
        class: Project\DefaultBundle\Services\Moderator
        arguments: ['@fhm_tools']

    fhm_cache:
        class: Project\DefaultBundle\Services\Cache
        arguments: ['@fhm_tools', '@session']