<?php
namespace Project\ProductBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Fhm\FhmBundle\Entity\Repository\FhmRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends FhmRepository
{
    /**
     * Constructor
     */
    public function __construct(EntityManager $dm, ClassMetadata $class)
    {
        parent::__construct($dm, $class);
    }
}