project_default:
    resource: "@ProjectDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

fhm_product:
    resource: "@FhmProductBundle/Controller/"
    type:     annotation
    prefix:   /