services:
    fhm_geocoder:
        class: Fhm\GeolocationBundle\Services\Geocoder
        arguments: ["@service_container"]

    fhm.twig.geolocation_extension:
        class: Fhm\GeolocationBundle\Twig\GeolocationExtension
        tags:
            - { name: twig.extension }

    fhm_map_controller:
        class: Fhm\GeolocationBundle\Controller\MapController
        arguments: ["@fhm_tools"]