services:
    fhm_geocoder:
        class: Fhm\GeolocationBundle\Services\Geocoder
#        arguments: ["@ivory.google_map.", "@ivory.google_map.geocoder"]

    fhm.twig.geolocation_extension:
        class: Fhm\GeolocationBundle\Twig\GeolocationExtension
        tags:
            - { name: twig.extension }